#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.0
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("KoloQR.Resource", IsApplication=true)]

namespace KoloQR
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::ZXing.Mobile.Resource.Id.contentFrame = global::KoloQR.Resource.Id.contentFrame;
			global::ZXing.Mobile.Resource.Layout.zxingscanneractivitylayout = global::KoloQR.Resource.Layout.zxingscanneractivitylayout;
			global::ZXing.Mobile.Resource.Layout.zxingscannerfragmentlayout = global::KoloQR.Resource.Layout.zxingscannerfragmentlayout;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int button_04A = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int icon2 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int KoloQR = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int logo = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int odczyt = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int przeglad = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int splash = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int star_rating_icon_2 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int star_rating_icon_3 = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int star_rating_icon_4 = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int star_rating_icon_5 = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int wyjscie = 2130837516;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060011
			public const int Label4Id = 2131099665;
			
			// aapt resource value: 0x7f060006
			public const int button1 = 2131099654;
			
			// aapt resource value: 0x7f06001b
			public const int contentFrame = 2131099675;
			
			// aapt resource value: 0x7f060016
			public const int data = 2131099670;
			
			// aapt resource value: 0x7f060005
			public const int editText1 = 2131099653;
			
			// aapt resource value: 0x7f060003
			public const int editText2 = 2131099651;
			
			// aapt resource value: 0x7f060014
			public const int grafikaOcena = 2131099668;
			
			// aapt resource value: 0x7f060008
			public const int imageView1 = 2131099656;
			
			// aapt resource value: 0x7f060001
			public const int linLayoutLogin = 2131099649;
			
			// aapt resource value: 0x7f060007
			public const int linLayoutLoginX = 2131099655;
			
			// aapt resource value: 0x7f060015
			public const int linearLayout1 = 2131099669;
			
			// aapt resource value: 0x7f060018
			public const int linearLayout2 = 2131099672;
			
			// aapt resource value: 0x7f060012
			public const int listView1 = 2131099666;
			
			// aapt resource value: 0x7f06000d
			public const int nazwaSprawdzianuLabel = 2131099661;
			
			// aapt resource value: 0x7f06000e
			public const int ocena = 2131099662;
			
			// aapt resource value: 0x7f060009
			public const int opcja1 = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int opcja2 = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int opcja3 = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int przedmiot = 2131099660;
			
			// aapt resource value: 0x7f060019
			public const int przedmiotOcena = 2131099673;
			
			// aapt resource value: 0x7f060017
			public const int przedmiotSprawdzian = 2131099671;
			
			// aapt resource value: 0x7f06001a
			public const int przedmiotUwagi = 2131099674;
			
			// aapt resource value: 0x7f060013
			public const int relativeLayout1 = 2131099667;
			
			// aapt resource value: 0x7f060000
			public const int textView1 = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int textView2 = 2131099650;
			
			// aapt resource value: 0x7f060004
			public const int textView3 = 2131099652;
			
			// aapt resource value: 0x7f06000f
			public const int textView5 = 2131099663;
			
			// aapt resource value: 0x7f060010
			public const int uwaga = 2131099664;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int History = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Login = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int LoginX = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int MainMenu = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Rating = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int ShowList = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Subject = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int zxingscanneractivitylayout = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int zxingscannerfragmentlayout = 2130903049;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			// aapt resource value: 0x7f040012
			public const int avg = 2130968594;
			
			// aapt resource value: 0x7f040013
			public const int choseSub = 2130968595;
			
			// aapt resource value: 0x7f040005
			public const int commit = 2130968581;
			
			// aapt resource value: 0x7f040011
			public const int defWarn = 2130968593;
			
			// aapt resource value: 0x7f040010
			public const int five = 2130968592;
			
			// aapt resource value: 0x7f04000e
			public const int four = 2130968590;
			
			// aapt resource value: 0x7f04000f
			public const int fourP = 2130968591;
			
			// aapt resource value: 0x7f040006
			public const int hello = 2130968582;
			
			// aapt resource value: 0x7f040002
			public const int index = 2130968578;
			
			// aapt resource value: 0x7f040004
			public const int login = 2130968580;
			
			// aapt resource value: 0x7f040007
			public const int main = 2130968583;
			
			// aapt resource value: 0x7f040003
			public const int pass = 2130968579;
			
			// aapt resource value: 0x7f040009
			public const int rating = 2130968585;
			
			// aapt resource value: 0x7f040008
			public const int subject = 2130968584;
			
			// aapt resource value: 0x7f04000c
			public const int three = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public const int threeP = 2130968589;
			
			// aapt resource value: 0x7f04000b
			public const int two = 2130968587;
			
			// aapt resource value: 0x7f04000a
			public const int warnings = 2130968586;
			
			// aapt resource value: 0x7f040001
			public const int zaloguj = 2130968577;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050001
			public const int Prezentacja = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int TekstZwykly = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int Theme_Splash = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
